# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DOCKER_POSTGRESS_USER}"
      POSTGRES_PASSWORD: "${DOCKER_POSTGRESS_PASSWORD}"
      POSTGRES_DB: "${DOCKER_POSTGRES_DB}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
    networks:
      - portifolio-brayan-divbrands-network
  app:
    image: portifolio-brayan-divbrands
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command:
      - sh
      - -c
      - |
        echo "Running"
        yarn prisma db push
        yarn dev
    networks:
      - portifolio-brayan-divbrands-network
networks:
  portifolio-brayan-divbrands-network:
    driver: bridge
