import type { Metadata } from "next";

import "./globals.css";

import { DarkThemeProvider } from "@/layout/DarkThemeProvider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html className="scroll-smooth" lang="en" suppressHydrationWarning>
        <head />
        <body>
          <DarkThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </DarkThemeProvider>
        </body>
      </html>
    </>
  );
}
