import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DarkThemeProvider } from "@/layout/DarkThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html className="scroll-smooth" lang="en" suppressHydrationWarning>
        <head />
        <body>
          <DarkThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </DarkThemeProvider>
        </body>
      </html>
    </>
  );
}
